### ISSUE TITLE
AttributeError: 'SemSegRandomSampler' object has no attribute 'cloud_id'

### ISSUE THREAD

**Issue by Gaoyuan2** [wymqqq/IKDNet-pytorch#1]
Hello,I'm learning your code.When I test my checkpoint,it has some issues.I had searched google,but I can't find the solution.Can you help me?

![图片](https://github.com/wymqqq/IKDNet-pytorch/assets/73592096/32beb3f8-108b-4204-8942-b1cd75ffd901)

**Comment by wymqqq** [comment]
Please use another function named "run_test_img" of the same Class for testing purposes.

> https://github.com/wymqqq/IKDNet-pytorch/blob/4ee73ac0163773f7a416654556719d7661e48321/ml3d/torch/pipelines/semantic_segmentation_dual.py#L188

**Comment by Gaoyuan2** [comment]
Thank you very much. I have solved the problem. I wish you many papers.
