### ISSUE TITLE
关于N3C-California Dataset的疑问

### ISSUE THREAD

**Issue by jikedream** [wymqqq/IKDNet-pytorch#4]
首先非常感谢您杰出的工作，我目前的方向是多模态遥感分割，看到您发布的N3C-California Dataset我尝试用这个数据集跑实验，但是下载解压之后DSM图像与RGB图像都失效了
![image](https://github.com/user-attachments/assets/02f6464f-3634-422c-9b60-e6a22a2156dc)
打开之后的效果如上图，想知道是我哪一步做的不对吗？

**Comment by wymqqq** [comment]
你好，tif影像需要用专门的遥感软件（如QGIS、ArcGIS）查看。

**Comment by jikedream** [comment]
> 你好，tif影像需要用专门的遥感软件（如QGIS、ArcGIS）查看。

好的感谢
